#!/usr/bin/env node
/**
 * Generates src/web/ui-assets.ts by embedding the UI files as string constants.
 * Run this whenever the UI under src/web/ui/ changes (also runs automatically
 * before build). Embedding makes the proxy self-contained — no on-disk UI dir is
 * needed at runtime, so both `tsx` runs and packaged single-file binaries work.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const uiDir = join(root, "src", "web", "ui");
const out = join(root, "src", "web", "ui-assets.ts");

const files = {
  indexHtml: "index.html",
  appJs: "app.js",
  styleCss: "style.css",
};

let body = `// AUTO-GENERATED by scripts/embed-ui.mjs — do not edit by hand.\n`;
body += `// Run \`npm run gen:ui\` after changing files in src/web/ui/.\n\n`;
for (const [name, file] of Object.entries(files)) {
  const content = readFileSync(join(uiDir, file), "utf8");
  body += `export const ${name} = ${JSON.stringify(content)};\n`;
}

writeFileSync(out, body);
console.log(`Embedded ${Object.keys(files).length} UI assets → ${out}`);
