/**
 * Web inspector — a node:http + ws app that exposes the live flow stream over a WebSocket and
 * a small REST API for detail/control (intercept resume/kill, replay, mark, options, rules).
 * Serves a single-page UI for browsing captured traffic.
 */

import { createServer, type Server, type IncomingMessage, type ServerResponse } from "node:http";
import { WebSocketServer, type WebSocket } from "ws";
import { readFileSync } from "node:fs";
import type { ProxyServer } from "../core/proxy.ts";
import type { Flow } from "../flow/flow.ts";
import { Headers } from "../flow/headers.ts";
import { flowsToHar } from "../flow/har.ts";
import { parseCurl, generateCode, type RequestSpec, type CodeLang } from "../api/composer.ts";
import { diffFlows } from "../api/diff.ts";
import type { Workspace } from "../api/workspace.ts";
import { log } from "../logger.ts";

// UI assets are embedded as string constants (generated by scripts/embed-ui.mjs) so the proxy
// is self-contained — no on-disk UI directory at runtime, works under tsx and packaged binaries.
import { indexHtml, appJs, styleCss } from "./ui-assets.ts";

const UI_ASSETS: Record<string, { body: string; type: string }> = {
  "index.html": { body: indexHtml, type: "text/html; charset=utf-8" },
  "app.js": { body: appJs, type: "application/javascript; charset=utf-8" },
  "style.css": { body: styleCss, type: "text/css; charset=utf-8" },
};

export class WebInspector {
  private server?: Server;
  private wss?: WebSocketServer;
  private sockets = new Set<WebSocket>();
  private boundPort = 0;

  constructor(private proxy: ProxyServer) {}

  get port(): number {
    return this.boundPort;
  }

  start(): Promise<void> {
    const host = this.proxy.options.get("webHost");
    const port = this.proxy.options.get("webPort");
    const self = this;

    this.wireStore();

    this.server = createServer((req, res) => {
      void this.handleNodeRequest(req, res);
    });

    // WebSocket endpoint (/ws): live flow stream.
    this.wss = new WebSocketServer({ noServer: true });
    this.server.on("upgrade", (req, socket, head) => {
      const pathname = new URL(req.url ?? "/", "http://localhost").pathname;
      if (pathname !== "/ws") {
        socket.destroy();
        return;
      }
      this.wss!.handleUpgrade(req, socket, head, (ws) => {
        self.sockets.add(ws);
        // Send the current snapshot so a fresh tab is immediately populated.
        ws.send(JSON.stringify({ type: "snapshot", flows: self.proxy.store.list().map((f) => f.toSummary()) }));
        ws.on("close", () => self.sockets.delete(ws));
        ws.on("error", () => self.sockets.delete(ws));
      });
    });

    return new Promise((resolve, reject) => {
      this.server!.once("error", reject);
      this.server!.listen(port, host, () => {
        this.server!.removeListener("error", reject);
        this.boundPort = (this.server!.address() as { port: number }).port;
        log.banner(`Web inspector → http://${host}:${this.boundPort}`);
        resolve();
      });
    });
  }

  stop(): void {
    for (const ws of this.sockets) {
      try {
        ws.close();
      } catch {
        /* ignore */
      }
    }
    this.sockets.clear();
    this.wss?.close();
    this.server?.close();
  }

  /** Import a Postman collection (v2.1) and replay each request to create flows. */
  private importPostman(collection: Record<string, unknown>): number {
    if (!collection || typeof collection !== "object") return 0;
    const items = (collection.item ?? []) as Array<Record<string, unknown>>;
    let count = 0;
    const walk = (entries: Array<Record<string, unknown>>): void => {
      for (const entry of entries) {
        // Nested folders contain sub-items
        const subItems = entry.item as Array<Record<string, unknown>> | undefined;
        if (Array.isArray(subItems)) {
          walk(subItems);
          continue;
        }
        const req = entry.request as Record<string, unknown> | undefined;
        if (!req) continue;
        const method = (req.method as string ?? "GET").toUpperCase();
        let rawUrl: string;
        const urlObj = req.url as Record<string, unknown> | string | undefined;
        if (typeof urlObj === "object" && urlObj !== null) {
          rawUrl = [urlObj.protocol, "://", urlObj.host, urlObj.path].flat().filter(Boolean).join("").replace(/^\/\//, (urlObj.protocol as string ?? "https") + "://");
          // Fallback: construct from raw
          if (!rawUrl && urlObj.raw) rawUrl = urlObj.raw as string;
        } else {
          rawUrl = (urlObj ?? "") as string;
        }
        if (!rawUrl) continue;
        // Ensure scheme
        if (!/^https?:\/\//i.test(rawUrl)) rawUrl = "https://" + rawUrl;

        const headers: Array<[string, string]> = [];
        const hdrArr = req.header as Array<Record<string, string>> | undefined;
        if (Array.isArray(hdrArr)) {
          for (const h of hdrArr) {
            if (h.key && h.value) headers.push([h.key, h.value]);
          }
        }
        const body = req.body as Record<string, unknown> | undefined;
        const bodyText = body?.raw as string ?? "";

        // Compose the request through the proxy engine
        try {
          void this.proxy.compose({ method, url: rawUrl, headers, body: bodyText });
          count++;
        } catch {
          // skip invalid requests
        }
      }
    };
    walk(items);
    return count;
  }

  /** Adapt a Node req/res pair to the Web Request/Response handlers. */
  private async handleNodeRequest(req: IncomingMessage, res: ServerResponse): Promise<void> {
    try {
      const url = new URL(req.url ?? "/", "http://localhost");

      if (req.method === "OPTIONS") {
        res.writeHead(204, {
          "access-control-allow-origin": "*",
          "access-control-allow-methods": "GET, POST, PUT, DELETE, OPTIONS",
          "access-control-allow-headers": "content-type",
        });
        res.end();
        return;
      }

      const webReq = await nodeReqToWebRequest(req, url);
      const webRes = await this.handleHttp(webReq, url);
      webRes.headers.set("access-control-allow-origin", "*");
      await writeWebResponse(res, webRes);
    } catch (e) {
      log.debug("web inspector request error:", (e as Error).message);
      if (!res.headersSent) res.writeHead(500);
      res.end();
    }
  }

  private wireStore(): void {
    const broadcast = (type: string, flow?: Flow) => {
      const msg = JSON.stringify(flow ? { type, flow: flow.toSummary() } : { type });
      for (const ws of this.sockets) {
        try {
          ws.send(msg);
        } catch {
          /* dropped client */
        }
      }
    };
    this.proxy.store.on("add", (f: Flow) => broadcast("add", f));
    this.proxy.store.on("update", (f: Flow) => broadcast("update", f));
    this.proxy.store.on("intercept", (f: Flow) => broadcast("intercept", f));
    this.proxy.store.on("clear", () => broadcast("clear"));
  }

  private async handleHttp(req: Request, url: URL): Promise<Response> {
    const { pathname } = url;

    // ---- static assets (embedded in the binary) ----
    const assetName = pathname === "/" ? "index.html" : pathname.slice(1);
    const asset = UI_ASSETS[assetName];
    if (asset) return new Response(asset.body, { headers: { "content-type": asset.type } });

    // ---- root CA download (one-click trust install) ----
    if (pathname === "/ca.crt" || pathname === "/cnproxy-ca.crt") {
      return new Response(readFileSync(this.proxy.ca.rootCertPath), {
        headers: {
          "content-type": "application/x-x509-ca-cert",
          "content-disposition": 'attachment; filename="cnproxy-ca.crt"',
        },
      });
    }

    // ---- mobile setup page (scan QR from inspector) ----
    if (pathname === "/setup") {
      const host = this.proxy.options.get("host") as string;
      const port = this.boundPort || this.proxy.options.get("webPort") as number;
      const proxyPort = this.proxy.port;
      const listenHost = host === "0.0.0.0" || host === "::" ? this.proxy.getLocalIp() || host : host;
      const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CNProxy Setup</title>
<style>body{font-family:system-ui,sans-serif;max-width:500px;margin:40px auto;padding:0 20px;color:#333;background:#f5f5f5}
.card{background:#fff;border-radius:12px;padding:24px;box-shadow:0 2px 8px rgba(0,0,0,.1);margin-bottom:20px}
h1{font-size:20px;margin:0 0 8px}h2{font-size:16px;margin:20px 0 8px;color:#4ea1ff}
.config{background:#f0f4f8;border-radius:8px;padding:12px;margin:12px 0;font-family:monospace}
.config div{display:flex;justify-content:space-between;padding:4px 0}
.config span{color:#666}.config b{color:#4ea1ff;font-size:16px}
ol{padding-left:20px;line-height:1.8}code{background:#f0f4f8;padding:2px 6px;border-radius:4px;font-size:14px}
.step{margin:4px 0}.tip{background:#fff3cd;border-left:3px solid #ffc107;padding:8px 12px;border-radius:4px;font-size:13px;margin:12px 0}
a{color:#4ea1ff}button{background:#4ea1ff;color:#fff;border:none;padding:10px 20px;border-radius:8px;font-size:16px;cursor:pointer;margin:8px 4px}
button:active{opacity:.8}.ca-btn{display:block;width:100%;text-align:center;margin:8px 0}</style></head><body>
<div class="card"><h1>⚡ CNProxy Mobile Setup</h1><p>Configure your device to use CNProxy as the Wi-Fi proxy.</p>
<div class="config"><div><span>Server</span><b>${listenHost}</b></div><div><span>Port</span><b>${proxyPort}</b></div></div>
<a class="ca-btn" href="/ca.crt" download><button>📥 Install CA Certificate</button></a>
</div>
<div class="card"><h2>📱 iPhone / iPad</h2><ol>
<li class="step">Open <strong>Settings → Wi-Fi</strong></li>
<li class="step">Tap the <strong>⓵</strong> button next to your connected network</li>
<li class="step">Scroll to <strong>HTTP Proxy</strong> → select <strong>Manual</strong></li>
<li class="step">Server: <code>${listenHost}</code></li>
<li class="step">Port: <code>${proxyPort}</code></li>
<li class="step">Tap <strong>Save</strong></li>
<li class="step">After connecting, download the CA cert above</li>
<li class="step">Go to <strong>Settings → General → VPN & Device Management</strong> → Install the profile</li>
<li class="step">Go to <strong>Settings → General → About → Certificate Trust Settings</strong> → Enable CNProxy Root CA</li>
</ol></div>
<div class="card"><h2>🤖 Android</h2><ol>
<li class="step">Open <strong>Settings → Wi-Fi</strong></li>
<li class="step">Long-press your network → <strong>Edit network</strong></li>
<li class="step">Expand <strong>Advanced</strong> → <strong>Proxy → Manual</strong></li>
<li class="step">Hostname: <code>${listenHost}</code></li>
<li class="step">Port: <code>${proxyPort}</code></li>
<li class="step">Save, then download the CA cert above</li>
<li class="step">Open the downloaded cert → <strong>Settings → Security → Install from storage</strong></li>
</ol>
<div class="tip"><strong>Note:</strong> Android 7+ apps don't trust user CAs by default. For debugging specific apps, use <code>networkSecurityConfig</code> or root + Magisk module.</div></div>
<div class="card"><h2>✅ Verify</h2><p>Visit any website in your mobile browser. Then check the <a href="/">CNProxy Inspector</a> to see captured traffic.</p></div>
</body></html>`;
      return new Response(html, { headers: { "content-type": "text/html; charset=utf-8" } });
    }

    // ---- setup API for programmatic access ----
    if (pathname === "/api/setup") {
      const host = this.proxy.options.get("host") as string;
      const proxyPort = this.proxy.port;
      const webPort = this.boundPort || this.proxy.options.get("webPort") as number;
      const listenHost = host === "0.0.0.0" || host === "::" ? this.proxy.getLocalIp() || host : host;
      return new Response(JSON.stringify({
        proxyHost: listenHost,
        proxyPort,
        webPort,
        caCertUrl: `http://${listenHost}:${webPort}/ca.crt`,
        inspectorUrl: `http://${listenHost}:${webPort}/`,
      }), { headers: { "content-type": "application/json", "access-control-allow-origin": "*" } });
    }

    // ---- REST API ----
    if (pathname.startsWith("/api/")) return this.handleApi(req, url);

    return new Response("Not found", { status: 404 });
  }

  private async handleApi(req: Request, url: URL): Promise<Response> {
    const { pathname } = url;
    const store = this.proxy.store;

    if (pathname === "/api/flows" && req.method === "GET") {
      return json(store.list().map((f) => f.toSummary()));
    }

    if (pathname === "/api/export/har" && req.method === "GET") {
      const har = flowsToHar(store.list(), this.proxy.version);
      return new Response(JSON.stringify(har, null, 2), {
        headers: {
          "content-type": "application/json; charset=utf-8",
          "content-disposition": 'attachment; filename="cnproxy.har"',
        },
      });
    }

    if (pathname === "/api/import/har" && req.method === "POST") {
      const har = await req.json().catch(() => null);
      const count = this.proxy.importHar(har);
      return json({ ok: true, flows: count });
    }

    // Import Postman collection (v2.1)
    if (pathname === "/api/import/postman" && req.method === "POST") {
      const collection = await req.json().catch(() => null);
      const count = this.importPostman(collection);
      return json({ ok: true, flows: count });
    }

    if (pathname === "/api/flows/replay-batch" && req.method === "POST") {
      const body = (await req.json().catch(() => ({}))) as { ids?: string[] };
      const ids = Array.isArray(body.ids) ? body.ids : [];
      const replayed = await Promise.all(ids.map((id) => this.proxy.replay(id)));
      return json({ ok: true, replayed: replayed.filter(Boolean).length });
    }

    if (pathname === "/api/flows/delete-batch" && req.method === "POST") {
      const body = (await req.json().catch(() => ({}))) as { ids?: string[] };
      const ids = Array.isArray(body.ids) ? body.ids : [];
      let deleted = 0;
      for (const id of ids) { if (store.remove(id)) deleted++; }
      return json({ ok: true, deleted });
    }

    // ---- API testing: composer / cURL / workspace ----
    if (pathname === "/api/compose" && req.method === "POST") {
      const spec = (await req.json().catch(() => null)) as RequestSpec | null;
      if (!spec?.url) return json({ error: "url required" }, 400);
      const flow = await this.proxy.compose(spec);
      return json(flow.toDetail());
    }
    if (pathname === "/api/curl/parse" && req.method === "POST") {
      const body = (await req.json().catch(() => ({}))) as { command?: string };
      return json(parseCurl(body.command ?? ""));
    }
    if (pathname === "/api/diff" && req.method === "GET") {
      const a = store.get(url.searchParams.get("a") ?? "");
      const b = store.get(url.searchParams.get("b") ?? "");
      if (!a || !b) return json({ error: "both flow ids required" }, 404);
      return json(diffFlows(a, b));
    }
    if (pathname === "/api/workspace") {
      if (req.method === "GET") return json(this.proxy.loadWorkspace());
      if (req.method === "PUT") {
        const ws = (await req.json().catch(() => null)) as Workspace | null;
        if (!ws) return json({ error: "invalid workspace" }, 400);
        this.proxy.saveWorkspace(ws);
        return json({ ok: true });
      }
    }

    if (pathname === "/api/clear" && req.method === "POST") {
      store.clear();
      return json({ ok: true });
    }

    // ---- session persistence / history ----
    if (pathname === "/api/sessions" && req.method === "GET") {
      return json(this.proxy.listSessions());
    }
    if (pathname === "/api/sessions/save" && req.method === "POST") {
      const body = (await req.json().catch(() => ({}))) as { name?: string };
      const name = body.name || `session-${store.list().length}`;
      const path = this.proxy.saveSession(name);
      return json({ ok: true, path });
    }
    if (pathname === "/api/sessions/load" && req.method === "POST") {
      const body = (await req.json().catch(() => ({}))) as { name?: string };
      if (!body.name) return json({ error: "name required" }, 400);
      const count = this.proxy.loadSession(body.name);
      return json({ ok: true, flows: count });
    }

    if (pathname === "/api/options") {
      if (req.method === "GET") return json(this.proxy.options.toJSON());
      if (req.method === "POST") {
        const patch = (await req.json()) as Record<string, unknown>;
        this.proxy.options.update(patch as never);
        return json(this.proxy.options.toJSON());
      }
    }

    if (pathname === "/api/stats" && req.method === "GET") {
      const flows = store.list();
      return json({
        total: flows.length,
        rules: this.proxy.rules.count,
        intercept: this.proxy.options.get("intercept"),
        decryptHttps: this.proxy.options.get("decryptHttps"),
      });
    }

    // /api/flows/:id  and  /api/flows/:id/:action
    const m = pathname.match(/^\/api\/flows\/([^/]+)(?:\/([a-z-]+))?$/);
    if (m) {
      const id = m[1]!;
      const action = m[2];
      const flow = store.get(id);
      if (!flow) return json({ error: "not found" }, 404);

      if (!action && req.method === "GET") return json(flow.toDetail());
      if (!action && req.method === "DELETE") {
        store.remove(id);
        return json({ ok: true, id });
      }

      if (action === "code" && req.method === "GET") {
        const lang = (url.searchParams.get("lang") ?? "curl") as CodeLang;
        return new Response(generateCode(flow, ["curl", "fetch", "python"].includes(lang) ? lang : "curl"), {
          headers: { "content-type": "text/plain; charset=utf-8" },
        });
      }

      if (req.method === "POST") {
        switch (action) {
          case "edit": {
            // Mutate a (typically paused) flow's request/response before it is resumed/relayed.
            const patch = (await req.json().catch(() => ({}))) as FlowEditPatch;
            applyFlowEdit(flow, patch);
            store.update(flow);
            return json({ ok: true });
          }
          case "resume":
            flow.resume();
            store.update(flow);
            return json({ ok: true });
          case "kill":
            flow.kill();
            store.update(flow);
            return json({ ok: true });
          case "mark":
            flow.marked = !flow.marked;
            store.update(flow);
            return json({ ok: true, marked: flow.marked });
          case "replay": {
            const replayed = await this.proxy.replay(id);
            return json({ ok: !!replayed, id: replayed?.id ?? null });
          }
          case "ws-send": {
            const body = (await req.json().catch(() => ({}))) as { text?: string; toServer?: boolean };
            const ok = this.proxy.injectWs(id, Buffer.from(body.text ?? "", "utf8"), !!body.toServer);
            return json({ ok });
          }
        }
      }
    }

    return json({ error: "unknown endpoint" }, 404);
  }
}

interface FlowEditPatch {
  request?: {
    method?: string;
    path?: string;
    headers?: [string, string][];
    /** base64-encoded body */
    body?: string;
  };
  response?: {
    statusCode?: number;
    headers?: [string, string][];
    body?: string;
  };
  comment?: string;
}

/** Apply an editor patch to a flow (used for intercept editing + manual tweaks). */
function applyFlowEdit(flow: Flow, patch: FlowEditPatch): void {
  if (patch.request) {
    const r = patch.request;
    if (typeof r.method === "string") flow.request.method = r.method;
    if (typeof r.path === "string") flow.request.path = r.path;
    if (Array.isArray(r.headers)) flow.request.headers = new Headers(r.headers);
    if (typeof r.body === "string") flow.request.body = Buffer.from(r.body, "base64");
  }
  if (patch.response && flow.response) {
    const r = patch.response;
    if (typeof r.statusCode === "number") flow.response.statusCode = r.statusCode;
    if (Array.isArray(r.headers)) flow.response.headers = new Headers(r.headers);
    if (typeof r.body === "string") flow.response.body = Buffer.from(r.body, "base64");
  }
  if (typeof patch.comment === "string") flow.comment = patch.comment;
}

function json(data: unknown, status = 200): Response {
  return new Response(JSON.stringify(data), {
    status,
    headers: { "content-type": "application/json; charset=utf-8" },
  });
}

/** Convert a Node IncomingMessage into a Web Request (body buffered for non-GET). */
async function nodeReqToWebRequest(req: IncomingMessage, url: URL): Promise<Request> {
  const headers = new globalThis.Headers();
  for (const [k, v] of Object.entries(req.headers)) {
    if (Array.isArray(v)) for (const vv of v) headers.append(k, vv);
    else if (v != null) headers.set(k, v);
  }
  const method = req.method ?? "GET";
  let body: Buffer | undefined;
  if (method !== "GET" && method !== "HEAD") {
    const chunks: Buffer[] = [];
    for await (const c of req) chunks.push(c as Buffer);
    body = Buffer.concat(chunks);
  }
  const webReq = new Request(url.toString(), {
    method,
    headers,
    body: (body && body.length ? body : undefined) as BodyInit | undefined,
  });
  if (webReq.method !== method) {
    // Guard against undici normalizing methods differently across Node.js versions:
    // shadow the prototype getter with an own property so handleApi sees the correct value.
    Object.defineProperty(webReq, "method", { value: method, configurable: true, enumerable: false });
  }
  return webReq;
}

/** Write a Web Response back onto a Node ServerResponse. */
async function writeWebResponse(res: ServerResponse, webRes: Response): Promise<void> {
  const headers: Record<string, string> = {};
  webRes.headers.forEach((v, k) => {
    headers[k] = v;
  });
  res.writeHead(webRes.status, headers);
  const buf = Buffer.from(await webRes.arrayBuffer());
  res.end(buf);
}
